### ISSUE TITLE
aaaa

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener-attic/issues-foo#108]
## Which cluster is affected?

`Cluster Details Dashboard Link`: https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-core/shoots/sre-test-gcp/

## When did it happen or started to happen?

`Absolute`: 
`Relative`: 

## Help us categorise this issue for faster resolution:

/area               audit-logging auto-scaling backup certification control-plane cost delivery disaster-recovery documentation high-availability logging metering monitoring networking os performance quality security storage usability user-management
/component   gardener dashboard documentation
/kind               bug regression post-mortem
/os                  garden-linux suse-chost
/platform        alicloud aws azure gcp converged-cloud

/priority normal

**Comment by ghost** [comment]
@neo-liang-sap No more than 5 labels permitted, but 21 labels were given.

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided (domain garden.canary.k8s.ondemand.com) does not match this repository (domains dev.gardener.cloud.sap, garden.dev.k8s.ondemand.com). Please open the issue at the correct repository. You can invoke the cluster self-diagnosis yourself later with `/diag` on a separate line in a comment to this issue.

**Comment by ghost** [comment]
@neo-liang-sap The issue was assigned to you under `author-action`. Please unassign yourself when you are done. Thank you.
