### ISSUE TITLE
Testing for ping command improvement

### ISSUE THREAD

**Issue by etiennnr** [gardener-attic/issues-foo#180]
Please, DO NOT ask questions or request support here.

This repo is only for general landscape or cluster issues.

You can discuss general questions on Slack #sap-tech-gardener:

https://sap-cp.slack.com/archives/C9CEBQPGE

You can ask landspace-specific questions on Slack #sap-tech-gardener-canary:

https://sap-ti.slack.com/archives/CBV3JS9S4

Please follow the Slackiquette:
- DO NOT use @channel (there are many hundred members and we listen anyways)
- DO use threads when you can (to avoid spamming the main channel space)

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr Command "/ping @etiennnr " failed with "UnboundLocalError("local variable '_pyGitHub' referenced before assignment")".
<details>
<summary>Additional Information</summary>

```
Redacted in public. Check backend logs.
```
</details>

**Comment by ghost** [comment]
@etiennnr Command "/ping" failed with "UnboundLocalError("local variable '_pyGitHub' referenced before assignment")".
<details>
<summary>Additional Information</summary>

```
Redacted in public. Check backend logs.
```
</details>

**Comment by ghost** [comment]
@etiennnr Command "/ping" failed with "UnboundLocalError("local variable 'pyGitHub' referenced before assignment")".
<details>
<summary>Additional Information</summary>

```
Redacted in public. Check backend logs.
```
</details>

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr No arguments have been provided when at least 1 is required. Please try again with as least 1 person or label

**Comment by ghost** [comment]
@etiennnr Command "/ping area/networking" failed with "AttributeError("'dict' object has no attribute 'labels'")".
<details>
<summary>Additional Information</summary>

```
Redacted in public. Check backend logs.
```
</details>

**Comment by ghost** [comment]
@etiennnr No person was found with the provided arguments. Please make sure to provide a Github username (with the `@` sign) or a correct label name.

**Comment by ghost** [comment]
@etiennnr No person was found with the provided arguments. Please make sure to provide a Github username (with the `@` sign) or a correct label name.

**Comment by ghost** [comment]
@etiennnr No person was found with the provided arguments. Please make sure to provide a Github username (with the `@` sign) or a correct label name.

**Comment by ghost** [comment]
@etiennnr No person was found with the provided arguments. Please make sure to provide a Github username (with the `@` sign) or a correct label name.

**Comment by ghost** [comment]
@etiennnr Command "/ping area/networking" failed with "TypeError("unhashable type: 'dict'")".
<details>
<summary>Additional Information</summary>

```
Redacted in public. Check backend logs.
```
</details>

**Comment by ghost** [comment]
@etiennnr No person was found with the provided arguments. Please make sure to provide a Github username (with the `@` sign) or a correct label name.
