### ISSUE TITLE
Test cluster

### ISSUE THREAD

**Issue by etiennnr** [gardener-attic/issues-foo#181]
## Which cluster is affected?

[`Cluster Details Dashboard Link`: URL](https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-panoramix/shoots/sre-tools/)

## When did it happen or started to happen?

`Absolute`: 
`Relative`:

**Comment by ghost** [comment]
@etiennnr Oops, the dashboard link that you have provided (domain garden.canary.k8s.ondemand.com) does not match this repository (domains dev.gardener.cloud.sap, garden.dev.k8s.ondemand.com). Please open the issue at the correct repository, e.g. https://github.com//gardener-attic/issues-foo/issues/new/choose. You can invoke the cluster self-diagnosis yourself later with `/diag` on a separate line in a comment to this issue.

**Comment by ghost** [comment]
@etiennnr The issue was assigned to you under `author-action`. Please unassign yourself when you are done. Thank you.
