### ISSUE TITLE
test cluster 2

### ISSUE THREAD

**Issue by etiennnr** [gardener-attic/issues-foo#182]
## Which cluster is affected?

https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-panoramix/shoots/sre-tools/

## When did it happen or started to happen?

`Absolute`: 
`Relative`:

**Comment by ghost** [comment]
@etiennnr Oops, the dashboard link that you have provided refers to a project that I could not find. You can invoke the cluster self-diagnosis yourself later with `/diag` on a separate line in a comment to this issue.

**Comment by ghost** [comment]
@etiennnr The issue was assigned to you under `author-action`. Please unassign yourself when you are done. Thank you.

**Comment by ghost** [comment]
@gardener-robot Oops, the dashboard link that you have provided refers to a project that I could not find.

**Comment by ghost** [comment]
@gardener-robot Oops, the dashboard link that you have provided refers to a project that I could not find.

**Comment by ghost** [comment]
@gardener-robot Oops, the dashboard link that you have provided refers to a project that I could not find.

**Comment by ghost** [comment]
@gardener-robot Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner/admins are not users in this GitHub.
