### ISSUE TITLE
yet another 

### ISSUE THREAD

**Issue by etiennnr** [gardener-attic/issues-foo#188]
Please, DO NOT suggest or request enhancements here.

This repo is only for general landscape or cluster issues.

You can discuss enhancement requests on Slack #sap-tech-gardener:

https://sap-cp.slack.com/archives/C9CEBQPGE

Please follow the Slackiquette:
- DO NOT use @channel (there are many hundred members and we listen anyways)
- DO use threads when you can (to avoid spamming the main channel space)

Most probably, you will be asked to file an enhancement request here:
- Gardener: https://github.com/gardener/gardener/issues/new?labels=kind%2Fenhancement&template=feature.md
- Dashboard: https://github.com/gardener/dashboard/issues/new?labels=kind%2Fenhancement&template=enhancement_request.md
- Documentation: https://github.com/gardener/documentation/issues/new?labels=kind%2Fenhancement&template=enhancement_request.md

/assign
/status accepted

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 13 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 24 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 27 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 27 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 29 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 31 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 95 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 100 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 176 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 178 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by ghost** [comment]
@etiennnr This issue has not been touched since 296 work days. Please add a follow up comment and/or change the `status/` label.

**Comment by etiennnr** [comment]
this is a public test

**Comment by etiennnr** [comment]
test parctical 2
