### ISSUE TITLE
[sretestneo/sre-g-test]

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener-attic/issues-foo#64]
## Which cluster is affected?

`Link`: [sretestneo/sre-g-test](https://dashboard.garden.dev.k8s.ondemand.com/namespace/garden-sretestneo/shoots/sre-g-test)

## When did it happen or started to happen?
`Timestamp`: 2021-04-14T21:03:01Z

## Help us categorise this issue for faster resolution:

/priority normal

**Comment by ghost** [comment]
Ticket was in state `author-`/`owner-action` with no further response since 21 days and the cluster is `healthy`. Closing.
