### ISSUE TITLE
quota change test issue

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener-attic/issues-foo#66]
## What is the name of the affected project?
`Project`: https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-di-master/

## What quota needs to be adjusted? Omit new target value for auto-approval/increase by our bot!

`Quota`: shoot

## Help us categorise this issue for faster resolution:

/priority normal

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap Less than 7 days!!!.

**Comment by ghost** [comment]
@neo-liang-sap You requested quota again within one week, which is not allowed. Please apply later, thanks.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap You requested quota again within one week, which is not allowed. Please apply later, thanks.

**Comment by ghost** [comment]
@neo-liang-sap You requested quota again within one week, which is not allowed. Please apply later, thanks.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap You requested quota again within one week, which is not allowed. Please apply later, thanks.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap The project you entered could not be parsed.

**Comment by ghost** [comment]
@neo-liang-sap You requested quota again within one week, which is not allowed. Please apply later, thanks.

**Comment by ghost** [comment]
@neo-liang-sap The issue was assigned to you under `author-action`. Please unassign yourself when you are done. Thank you.

**Comment by ghost** [comment]
@gardener-robot Oops, the issue description doesn't contain a valid shoot cluster dashboard link.

**Comment by ghost** [comment]
<img src="https://source.unsplash.com/collection/4538752/640x513">
<details>
<summary>Message</summary>

> /ping
</details>

**Comment by ghost** [comment]
<img src="https://source.unsplash.com/collection/4538752/640x360">
<details>
<summary>Message</summary>

> /ping
</details>

**Comment by ghost** [comment]
<img src="https://source.unsplash.com/collection/4538752/640x509">
<details>
<summary>Message</summary>

> /ping
</details>

**Comment by ghost** [comment]
<img src="https://source.unsplash.com/collection/4538752/640x472">
<details>
<summary>Message</summary>

> /ping
</details>

**Comment by ghost** [comment]
<img src="https://source.unsplash.com/collection/4538752/640x522">
<details>
<summary>Message</summary>

> /ping
</details>

**Comment by ghost** [comment]
<img src="https://source.unsplash.com/collection/4538752/640x610">
<details>
<summary>Message</summary>

> /ping
</details>

**Comment by ghost** [comment]
Ticket was in state `author-`/`owner-action` with no further response since 21 days. Closing.

**Comment by ghost** [comment]
Quota increase was auto-approved. Closing ticket now.

**Comment by ghost** [comment]
Ticket was in state `author-`/`owner-action` with no further response since 21 days. Closing.
