### ISSUE TITLE
test issue - please ignore!!!!!

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener-attic/issues-foo#95]
## Which cluster is affected?

`Link`: [sretestneo/sre-g-test](https://dashboard.garden.dev.k8s.ondemand.com/namespace/garden-sretestneo/shoots/sre-g-test)

## When did it happen or started to happen?
`Timestamp`: 2021-04-14T21:03:01Z

## Help us categorise this issue for faster resolution:

/priority critical

**Comment by ghost** [comment]
@neo-liang-sap 

**Shoot:** [sretestneo/sre-g-test](https://dashboard.dev.gardener.cloud.sap/namespace/garden-sretestneo/shoots/sre-g-test) `v1.21.3`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;created at `2021-04-14 01:04` by `Neo Liang (BTP Core FP TS SRE&Observability (CHN))`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;on `aws` in `eu-west-1` with purpose `development`
**Seed:** [garden/aws](https://dashboard.dev.gardener.cloud.sap/namespace/garden/shoots/aws)
<details><summary>🟢 Last Operation</summary>

```
description: Shoot cluster state has been successfully reconciled.
lastUpdateTime: '2021-08-31T15:40:22Z'
progress: 100
state: Succeeded
type: Reconcile
```
</details>
<details><summary>🟢 Shoot Conditions</summary>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 APIServerAvailable (HealthzRequestSucceeded)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 ControlPlaneHealthy (ControlPlaneRunning)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 EveryNodeReady (EveryNodeReady)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 SystemComponentsHealthy (SystemComponentsRunning)
</details>
<details><summary>🟢 Seed Conditions</summary>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 GardenletReady (GardenletReady)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 Bootstrapped (BootstrappingSucceeded)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 ExtensionsReady (AllExtensionsReady)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 AuditlogServiceAvailability (AuditlogInstanceAttached)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🟢 BackupBucketsReady (BackupBucketsAvailable)
</details>
<details><summary>🟢 Worker Groups</summary>

| *Name* | *OS* | *Machine* | *Zones* |
| :- | :- | :- | :- |
| **`worker-i3q39`**<br/>`1:2`&nbsp;`-0`&nbsp;`+1` | `gardenlinux`<br/>`v318.8.0` | `m5.large`<br/>`50Gi`&nbsp;`gp2` | `eu-west-1b`<br/>&nbsp; |
</details>
<details><summary>🟠 Unhealthy Worker Nodes</summary>

| *Name* | *Usage* | *Conditions* |
| :- | :- | :- |
</details>
<details><summary>🟢 Control Plane</summary>

| *Name* | *Status* | *Age* |
| :- | :- | :- |
| **`cert-controller-manager`**`-7db6544564`<br/>`10.243.135.251` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 2 hours, 44 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`cloud-controller-manager`**`-5d785c9967`<br/>`10.243.138.232` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 7 hours, 11 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`cluster-autoscaler`**`-67fcc4c959`<br/>`10.243.155.172` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 15 hours, 58 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`csi-driver-controller`**`-75958d7d7b`<br/>`10.243.132.145` | Running<br/>🟢&nbsp;6/6&nbsp;Ready | 16 hours, 45 secs<br/>🟢&nbsp;0&nbsp;Restarts |
| **`csi-snapshot-controller`**`-7b5965678b`<br/>`10.243.155.54` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 12 hours, 28 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`etcd-events`**<br/>`10.243.135.103` | Running<br/>🟢&nbsp;2/2&nbsp;Ready | 9 hours, 56 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`etcd-main`**<br/>`10.243.153.22` | Running<br/>🟢&nbsp;2/2&nbsp;Ready | 16 hours, 15 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`gardener-resource-manager`**`-69cb9c9594`<br/>`10.243.155.192` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 8 hours, 37 mins<br/>🟢&nbsp;2&nbsp;Restarts |
| **`grafana-operators`**`-6c4dc76ff8`<br/>`10.243.155.254` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 12 hours, 58 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`grafana-users`**`-5b96994f77`<br/>`10.243.155.22` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 12 hours, 58 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`kube-apiserver`**`-8f5969c59`<br/>`10.243.132.142` | Running<br/>🟢&nbsp;2/2&nbsp;Ready | 16 hours, 47 secs<br/>🟢&nbsp;0&nbsp;Restarts |
| **`kube-controller-manager`**`-79b9768467`<br/>`10.243.155.74` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 7 hours, 10 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`kube-scheduler`**`-97c4cbc47`<br/>`10.243.135.133` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 12 hours, 32 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`kube-state-metrics`**`-765c89bc8c`<br/>`10.243.136.127` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 15 hours, 58 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`loki`**<br/>`10.243.132.112` | Running<br/>🟢&nbsp;4/4&nbsp;Ready | 12 hours, 57 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`machine-controller-manager`**`-6d6fbf869d`<br/>`10.243.138.241` | Running<br/>🟢&nbsp;2/2&nbsp;Ready | 7 hours, 11 mins<br/>🟢&nbsp;1&nbsp;Restart |
| **`prometheus`**<br/>`10.243.132.202` | Running<br/>🟢&nbsp;3/3&nbsp;Ready | 2 hours, 8 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`shoot-dns-service`**`-d564ccf54`<br/>`10.243.132.136` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 16 hours, 58 secs<br/>🟢&nbsp;0&nbsp;Restarts |
| **`vpa-admission-controller`**`-55754d77b7`<br/>`10.243.132.181` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 15 hours, 58 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`vpa-recommender`**`-59cd5c7c79`<br/>`10.243.136.119` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 12 hours, 58 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`vpa-updater`**`-5c9f47db46`<br/>`10.243.136.116` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 12 hours, 58 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`vpn-seed-server`**`-c955f7cdb`<br/>`10.243.135.74` | Running<br/>🟢&nbsp;2/2&nbsp;Ready | 9 hours, 56 mins<br/>🟢&nbsp;0&nbsp;Restarts |
</details>
<details><summary>🟠 System Components</summary>

| *Name* | *Status* | *Age* |
| :- | :- | :- |
| **`apiserver-proxy`**<br/>`10.250.6.79` | Running<br/>🟢&nbsp;2/2&nbsp;Ready | 15 hours, 59 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`blackbox-exporter`**`-59dd4794cf`<br/>`100.96.1.164` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 15 hours, 59 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`calico-kube-controllers`**`-7b4c5fb95`<br/>`100.96.1.136` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 2 days, 23 hours<br/>🟠&nbsp;*8&nbsp;Restarts* |
| **`calico-node`**<br/>`10.250.6.79` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 4 days, 12 hours<br/>🟢&nbsp;0&nbsp;Restarts |
| **`calico-node-vertical-autoscaler`**`-785b5f968`<br/>`100.96.1.162` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 4 days, 12 hours<br/>🟢&nbsp;0&nbsp;Restarts |
| **`calico-typha-deploy`**`-59966cd68c`<br/>`10.250.6.79` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 1 week, 4 days<br/>🟢&nbsp;0&nbsp;Restarts |
| **`calico-typha-horizontal-autoscaler`**`-5b58bb446c`<br/>`100.96.1.163` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 4 days, 12 hours<br/>🟢&nbsp;0&nbsp;Restarts |
| **`calico-typha-vertical-autoscaler`**`-5c9655cddd`<br/>`100.96.1.161` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 4 days, 12 hours<br/>🟢&nbsp;0&nbsp;Restarts |
| **`coredns`**`-79f7c4d78b`<br/>`100.96.1.167` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 12 hours, 31 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`coredns`**`-79f7c4d78b`<br/>`100.96.1.168` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 12 hours, 31 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`csi-driver-node`**<br/>`10.250.6.79` | Running<br/>🟢&nbsp;3/3&nbsp;Ready | 1 week, 12 hours<br/>🟢&nbsp;0&nbsp;Restarts |
| **`kube-proxy`**<br/>`10.250.6.79` | Running<br/>🟢&nbsp;2/2&nbsp;Ready | 15 hours, 59 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`metrics-server`**`-6776696f8`<br/>`100.96.1.156` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 15 hours, 59 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`node-exporter`**<br/>`10.250.6.79` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 15 hours, 59 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`node-problem-detector`**<br/>`100.96.1.165` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 15 hours, 59 mins<br/>🟢&nbsp;0&nbsp;Restarts |
| **`vpn-shoot`**`-5897486c5c`<br/>`100.96.1.159` | Running<br/>🟢&nbsp;1/1&nbsp;Ready | 15 hours, 59 mins<br/>🟢&nbsp;0&nbsp;Restarts |
</details>
<details><summary>🟢 Daemon Sets</summary>

| *Name* | *Namespace* | *Desired Number Scheduled* | *Number Ready* | *Number Unavailable* |
| :- | :- | :- | :- | :- |
| **apiserver-proxy**| kube-system| 1| 1| None |
| **calico-node**| kube-system| 1| 1| None |
| **csi-driver-node**| kube-system| 1| 1| None |
| **kube-proxy**| kube-system| 1| 1| None |
| **node-exporter**| kube-system| 1| 1| None |
| **node-problem-detector**| kube-system| 1| 1| None |
</details>
<details><summary>🟠 No pod disruption budgets (PDB) defined</summary>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Consequence:* Workload is unprotected from voluntary disruptions such as under node rolling updates
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Recommendation:* Protect your workload with proper PDBs (in combination with node anti-affinity)
</details>

**Comment by ghost** [comment]
@gardener-robot You have mentioned internal references in the public. Please check.

**Comment by ghost** [comment]
@abdasgupta, @ashwani2k ℹ️ Please take note of this issue.

**Comment by neo-liang-sap** [comment]
close as testing done

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by neo-liang-sap** [comment]
aaa

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by neo-liang-sap** [comment]
aaaaa

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by ghost** [comment]
@neo-liang-sap Oops, the dashboard link that you have provided refers to a cluster (or project) whose owner is not a user in this GitHub.

**Comment by ghost** [comment]
Ticket was in state `author-`/`owner-action` with no further response since 21 days and the cluster is `healthy`. Closing.
